CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

ALTER TABLE "Profiles" ALTER COLUMN "DatabasesUsed" DROP NOT NULL;

ALTER TABLE "Profiles" ALTER COLUMN "CurrentRole" TYPE text;

ALTER TABLE "Profiles" ADD "FirstName" text;

ALTER TABLE "Profiles" ADD "LastName" text;

CREATE TABLE "Project" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text NOT NULL,
    tools text[] NOT NULL,
    "StartDate" date,
    "EndDate" date,
    "ProfileId" integer,
    CONSTRAINT "PK_Project" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Project_Profiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id")
);

CREATE INDEX "IX_Project_ProfileId" ON "Project" ("ProfileId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240928171954_ProfileNew', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Profiles" ADD "Matches" integer NOT NULL DEFAULT 0;

ALTER TABLE "Profiles" ADD "Sessions" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241012153456_ProfileVideoMigrations', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Profiles" ADD "GithubUrl" text NOT NULL DEFAULT '';

ALTER TABLE "Profiles" ADD "LinkedInUrl" text NOT NULL DEFAULT '';

ALTER TABLE "Profiles" ADD "PortfolioUrl" text NOT NULL DEFAULT '';

ALTER TABLE "Profiles" ADD "TwitterUrl" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241012211923_ProfileUrls', '8.0.8');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241012212332_ProfileUrlsNew', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "DirectMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Profile1Id" integer NOT NULL,
    "Profile2Id" integer NOT NULL,
    CONSTRAINT "PK_DirectMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Text" text NOT NULL,
    "FromProfileId" integer NOT NULL,
    "DirectMessageId" integer NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241109034324_Messages', '8.0.8');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250120053047_InitialMigration', '8.0.8');

COMMIT;

