--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


SET default_table_access_method = heap;

--
-- Name: DirectMessages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DirectMessages" (
    "Id" integer NOT NULL,
    "Profile1Id" integer NOT NULL,
    "Profile2Id" integer NOT NULL
);


--
-- Name: DirectMessages_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."DirectMessages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DirectMessages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Messages" (
    "Id" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Text" text NOT NULL,
    "FromProfileId" integer NOT NULL,
    "DirectMessageId" integer NOT NULL
);


--
-- Name: Messages_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Messages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Messages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Profiles" (
    "Id" integer NOT NULL,
    "IdentityUserId" text NOT NULL,
    "ProgrammingLanguages" text[] NOT NULL,
    "Frameworks" text[] NOT NULL,
    "CurrentRole" text NOT NULL,
    "DatabasesUsed" text[],
    "Certifications" text[],
    "DevelopmentInterests" text[],
    "Languages" text[],
    "Avaliability" text DEFAULT ''::text NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL,
    "Industry" text,
    "FirstName" text,
    "LastName" text,
    "Matches" integer DEFAULT 0 NOT NULL,
    "Sessions" integer DEFAULT 0 NOT NULL,
    "GithubUrl" text DEFAULT ''::text NOT NULL,
    "LinkedInUrl" text DEFAULT ''::text NOT NULL,
    "PortfolioUrl" text DEFAULT ''::text NOT NULL,
    "TwitterUrl" text DEFAULT ''::text NOT NULL
);


--
-- Name: Profiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Profiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Profiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Project" (
    "Id" integer NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    tools text[] NOT NULL,
    "StartDate" date,
    "EndDate" date,
    "ProfileId" integer
);


--
-- Name: Project_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Project" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Project_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" text NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: DirectMessages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."DirectMessages" ("Id", "Profile1Id", "Profile2Id") FROM stdin;
5	1	2
6	12	1
7	13	1
\.


--
-- Data for Name: Messages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Messages" ("Id", "CreatedAt", "Text", "FromProfileId", "DirectMessageId") FROM stdin;
1	2024-11-09 13:32:14.871192-05	Hola, soy dora	12	6
2	2024-11-09 13:32:32.659838-05	Hola, soy dora	12	6
3	2024-11-09 13:32:34.311807-05	Hola, soy dora	12	6
4	2024-11-09 13:32:37.420187-05	Hola, soy dora	12	6
5	2024-11-09 15:06:31.632887-05	Hola soy dora	12	6
6	2024-11-09 15:09:15.3569-05	Hey there feller	12	6
7	2024-11-09 15:10:51.00511-05	wtf	12	6
8	2024-11-09 15:11:09.45372-05	wtf	12	6
9	2024-11-09 15:11:31.899348-05	huh	12	6
10	2024-11-09 15:12:13.383601-05	testing	12	6
11	2024-11-09 15:14:39.403902-05	hi	12	6
12	2024-11-09 15:15:13.423552-05	what is this	12	6
13	2024-11-09 15:16:46.282819-05	uhh	12	6
14	2024-11-09 15:17:39.646086-05	test	12	6
15	2024-11-09 15:18:33.629567-05	test	12	6
16	2024-11-09 15:19:01.573757-05	como te llamas	12	6
17	2024-11-09 15:21:01.002103-05	are there 2 connections	12	6
18	2024-11-09 15:22:01.520759-05	what is this	12	6
19	2024-11-09 15:22:29.077328-05	como te llamas	12	6
20	2024-11-09 15:24:02.454033-05	como te llamass	12	6
21	2024-11-09 15:24:55.607842-05	hola soy dora	12	6
22	2024-11-09 15:30:19.212871-05	Weolc	12	6
23	2024-11-09 15:30:38.160114-05	Welcome to the jungle	12	6
24	2024-11-09 15:31:26.126267-05	Hi buddy	12	6
25	2024-11-09 15:32:04.115637-05	Hi buddy	12	6
26	2024-11-09 15:33:20.65622-05	What is this	12	6
27	2024-11-09 15:34:41.963512-05	hola 	12	6
28	2024-11-09 15:35:17.711737-05	wut	12	6
29	2024-11-09 15:35:54.85741-05	Why wont this work	12	6
30	2024-11-09 15:36:18.307252-05	This should be in real time no?	12	6
31	2024-11-09 15:37:09.506941-05	Why not in real time	12	6
32	2024-11-09 16:07:02.876467-05	now real time	12	6
33	2024-11-09 16:07:30.040737-05	im a different client though	1	6
34	2024-11-09 16:07:55.517346-05	elmos world	12	6
35	2024-11-09 16:08:08.850746-05	shouldnt be twice	12	6
36	2024-11-09 16:08:28.054403-05	why two connections wtf	12	6
37	2024-11-09 16:10:48.448857-05	hopefully not 2	1	6
38	2024-11-09 16:18:04.041965-05	hello	12	6
39	2024-11-09 16:19:52.207631-05	can this message not be recieved twice?	12	6
40	2024-11-09 16:20:08.468197-05	why is it like this	12	6
41	2024-11-09 16:24:05.600168-05	hi	12	6
42	2024-11-16 11:07:55.990422-05	hallo	2	5
43	2024-11-16 11:08:07.7193-05	how you doing	2	5
44	2024-11-16 11:08:48.389482-05	you like pumpkins	2	5
45	2024-11-16 11:09:01.922808-05	or no	2	5
46	2024-11-16 11:09:07.358721-05	I like pumpkins	1	5
47	2024-11-16 11:11:15.600384-05	this live now	2	5
48	2024-11-16 11:12:18.485753-05	state is conserved	2	5
49	2024-11-16 11:12:43.460271-05	but not everytihn	1	5
50	2024-11-16 11:25:34.674639-05	halo	2	5
51	2024-11-16 11:25:45.319917-05	haa	2	5
52	2024-11-16 11:25:58.100559-05	bery stupid things	2	5
53	2024-11-16 11:26:06.835636-05	but its undefined	2	5
54	2024-11-16 11:38:46.112658-05	now this should not do twice	1	5
55	2024-11-16 11:39:03.636389-05	hopefully	1	5
56	2024-11-16 11:40:51.516156-05	hello	1	5
57	2024-11-16 11:41:13.32725-05	goodbye	2	5
58	2024-11-16 11:41:22.44845-05	why disconnect	2	5
59	2024-11-16 11:41:43.210332-05	why would it disconnect	2	5
60	2024-11-16 11:41:51.918839-05	so stupid	2	5
61	2024-11-16 11:42:40.890612-05	welcome to ny	1	5
62	2024-11-16 11:42:47.886627-05	its been waiting for you	1	5
63	2024-11-16 11:42:54.295422-05	welcome to ny	1	5
64	2024-11-16 11:43:04.240716-05	we been waiting for you to come for so long	1	5
65	2024-11-16 11:44:48.745722-05	why so serious	1	5
66	2024-11-16 11:48:31.171692-05	ready	1	5
67	2024-11-16 11:48:41.851485-05	its gonna be fun	2	5
68	2024-11-16 11:52:32.420585-05	interesting	1	5
69	2024-11-16 11:54:37.102276-05	so	2	5
70	2024-11-16 11:54:46.153281-05	I guess this wroks now	1	5
71	2024-11-16 11:54:52.719888-05	that is a good thing	1	5
72	2024-11-16 11:55:55.722492-05	can I make this smoother?	1	5
73	2024-11-16 11:55:58.706969-05	I wonder	1	5
74	2024-11-16 15:11:23.926753-05	how smooth	1	5
75	2024-11-16 15:11:54.764764-05	uhh	1	5
76	2024-11-16 15:13:07.802772-05	I guess this is temporary	1	5
77	2024-11-16 15:27:56.807471-05	huh	1	5
78	2024-11-16 21:18:38.530319-05	hi	1	5
79	2024-11-17 11:12:06.559823-05	hello	1	6
80	2024-11-17 11:12:17.833551-05	hi	1	6
81	2024-11-17 11:12:22.783804-05	hi	1	6
82	2024-11-17 11:12:28.355851-05	 cool	1	6
83	2024-11-17 11:12:37.316283-05	whats the lag	1	6
84	2024-11-17 11:13:31.732963-05	hello	1	6
85	2024-11-17 11:14:04.325495-05	someone typing	1	6
86	2024-11-17 11:15:19.55294-05	hey buddy	1	5
87	2024-11-17 11:15:53.489406-05	welcome	1	5
88	2024-11-17 11:21:44.239315-05	welcome to the thing	1	5
89	2024-11-17 11:21:56.337507-05	holy hell	1	5
90	2024-11-17 11:22:19.39079-05	this live	1	5
91	2024-11-17 11:22:31.277915-05	idk how this works	2	5
92	2024-11-17 11:23:35.522257-05	hello worlf	1	5
93	2024-11-17 11:23:40.94933-05	im sick of this	2	5
94	2024-11-17 11:23:48.408312-05	welcome to the thing	1	5
95	2024-11-17 11:23:48.781694-05	welcome to the thing	1	5
96	2024-11-17 11:23:53.377565-05	no dupes	2	5
97	2024-11-17 11:24:36.909323-05	weird ass thing	1	5
98	2024-11-17 11:24:44.196468-05	weird things	1	5
99	2024-11-17 11:24:49.261879-05	hello world	1	5
100	2024-11-17 11:26:12.738912-05	ive been driving	1	5
101	2024-11-17 11:26:17.904611-05	been running	1	5
102	2024-11-17 11:26:22.125813-05	through it all	1	5
103	2024-11-17 11:26:29.525759-05	try to find it and a  fnf	1	5
104	2024-11-17 11:29:59.348382-05	why is this needed to be valid	1	5
105	2024-11-17 11:30:23.013923-05	so is this	2	5
106	2024-11-17 11:30:28.52222-05	actually synched	1	5
107	2024-11-17 11:30:36.37654-05	welcome to the night	2	5
108	2024-11-17 11:35:52.936461-05	heck ye	1	5
109	2024-11-17 11:35:57.765752-05	i want it all now	2	5
110	2024-11-17 11:36:03.247296-05	hundred feedings	1	5
111	2024-11-17 11:39:53.302896-05	wecloe 	1	5
112	2024-11-17 11:39:58.030257-05	mosh pit	2	5
113	2024-11-17 11:57:28.139286-05	metro boomin make it boom	1	5
114	2024-11-17 12:06:02.494442-05	hey buddy	1	6
115	2024-11-20 23:36:01.168712-05	I am John	1	5
116	2024-11-20 23:37:16.423293-05	hello	1	5
117	2024-11-20 23:37:36.819919-05	this should be responsive	1	5
118	2024-11-20 23:40:03.264634-05	well	1	5
119	2024-11-20 23:41:03.32476-05	THis should be in real time	1	5
121	2024-11-20 23:41:59.170409-05	aint it	1	5
120	2024-11-20 23:41:50.77397-05	its cool	2	5
122	2024-11-20 23:49:40.478473-05	some errors	2	5
123	2024-11-20 23:52:45.913233-05	uhh	2	5
124	2024-11-21 09:59:53.139184-05	hallo	1	6
125	2025-01-18 18:56:32.823152-05	hi	2	5
126	2025-01-18 18:56:37.339748-05	this live	2	5
127	2025-01-18 21:33:59.423385-05	I think so	2	5
128	2025-01-18 21:34:05.939239-05	Its cool	2	5
129	2025-01-18 21:36:41.124856-05	uhh	2	5
130	2025-01-18 21:36:47.036831-05	hi	2	5
131	2025-01-18 21:38:57.766668-05	ihh	2	5
132	2025-01-18 21:39:04.049099-05	hi	2	5
133	2025-01-18 21:40:04.486956-05	hi	2	5
134	2025-01-18 21:40:11.828761-05	uhh	2	5
135	2025-01-18 21:40:35.907374-05	hello	2	5
136	2025-01-18 21:40:43.708621-05	cool	2	5
137	2025-01-18 21:41:40.78779-05	hi	2	5
138	2025-01-18 21:41:53.890093-05	hi	2	5
139	2025-01-18 21:42:00.205013-05	hi	2	5
140	2025-01-18 21:42:10.810583-05	welp	2	5
141	2025-01-18 21:42:36.979531-05	hi	2	5
142	2025-01-18 21:42:43.450552-05	sim	2	5
143	2025-01-18 21:42:50.897711-05	what	2	5
144	2025-01-19 17:52:31.88611-05	yo	13	7
145	2025-01-19 17:52:53.586447-05	wasup	13	7
146	2025-01-19 22:55:17.128418-05	hi	13	7
147	2025-01-19 23:00:11.287266-05	cool	2	5
\.


--
-- Data for Name: Profiles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Profiles" ("Id", "IdentityUserId", "ProgrammingLanguages", "Frameworks", "CurrentRole", "DatabasesUsed", "Certifications", "DevelopmentInterests", "Languages", "Avaliability", "Description", "Industry", "FirstName", "LastName", "Matches", "Sessions", "GithubUrl", "LinkedInUrl", "PortfolioUrl", "TwitterUrl") FROM stdin;
11	9d09426c-2ca7-45c1-a257-b5745b615451	{Java,C#,C++}	{test,ASP.NET,Django,Express.js}	Full Stack Developer	\N	\N	{Cybersecurity,"Cloud Computing"}	\N	Full Time	Professional in AWS Cloud Security and VPCs. Specializing in DDOS protection and DOS attacks.	Data Science	John	Doe	0	35				
1	9f99e4a9-a0fc-4c12-b679-2dd318572127	{"[\\"Java\\", \\"Python\\"]",Python,C++,Go,Java}	{" [\\"Spring\\", \\"React\\"]",ASP.NET,Express.js,FastAPI}	Cloud Architect	{" [\\"PostgreSQL\\"]"}	{" [\\"AWS Certified Developer\\"]"}	{" [\\"Dev Ops\\"]","Cloud Computing",Blockchain,"Artificial Intelligence (AI)"}	{" [\\"English\\"],"}	Part-Time	 Experienced Java developer	Environmental Services	John	Doe	0	340	https://github.com/kaane5662/	http://www.linkedin.com/in/kaan-eren-29600a304	https://kaan-portfolio.netlify.app/	
12	65637ba6-4289-4d41-be59-5b62468b0b26	{JavaScript,Go,Python,C#}	{test,ASP.NET,Django,Express.js,FastAPI,Flask}	Security Engineer	\N	\N	{"Cloud Computing",Cybersecurity,"Machine Learning"}	\N	Part-Time	Aspiring Cyber Security engineer looking for partners to work on an AWS project.	Data Science	Khan	Ahmed	0	337	https://github.com/kaane5662/		https://kaan-portfolio.netlify.app/	https://kaan-portfolio.netlify.app/
13	5940e327-bd5c-4749-a5e8-609f5f46bfc5	{C#,TypeScript,JavaScript,C++}	{test,Django,Express.js,Next.js,PyTorch}	Back-End Developer	\N	\N	{Blockchain,"Cloud Computing","Internet of Things (IoT)"}	\N	Full Time	Professional backend developer with microservices looking to make a cold reach out startup	Marketing	Mark	Doe	0	19				
2	9fb25064-8a63-4c39-a33e-4ee607f1fd33	{Python,JavaScript,TypeScript}	{" [\\"DotnetCore\\", \\"React\\"]",ASP.NET,Django,Express.js}	Full Stack Developer	{" [\\"PostgreSQL\\"]"}	{" [\\"AWS Certified Developer\\"]"}	{"Artificial Intelligence (AI)","Machine Learning","Web Development"}	{" [\\"English\\"],"}	Part-Time	This is just a test to see if my new profile gets saved.	Data Science	Kaan	Eren	0	276	https://github.com/kaane5662/			
14	046e9ff1-dbd7-4ea4-9bab-e3200a7ceef7	{C#,TypeScript,Java}	{ASP.NET,Django,FastAPI,Express.js,React}	Cloud Architect	\N	\N	{"Cloud Computing"}	\N	Full Time	Experienced cloud developer with over 5 years of experience trying to find technical partners to create a startup	E-commerce	Michael	Davydov	0	0				
\.


--
-- Data for Name: Project; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Project" ("Id", title, description, tools, "StartDate", "EndDate", "ProfileId") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Users" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
9f99e4a9-a0fc-4c12-b679-2dd318572127	\N	\N	test1@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	62d3d359-21f4-4eff-97da-541d2c696794	e1179496-917f-4a5c-948e-6611d952dbd6	\N	f	f	\N	f	0
9fb25064-8a63-4c39-a33e-4ee607f1fd33	\N	\N	test2@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	e11701ff-bb41-4280-a756-bc4cd500ead8	8568be64-3443-448d-8986-af84947a7303	\N	f	f	\N	f	0
ab139671-5e92-4acd-8bf4-0ec0d25fa85f	\N	\N	test4@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	1602c0d6-8d71-4823-811d-6718f2458d70	170409eb-6c8d-4b70-81f0-b206da0f3ffc	\N	f	f	\N	f	0
9d09426c-2ca7-45c1-a257-b5745b615451	\N	\N	test5@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	bba2341a-4e02-421f-9a5b-451dc17d49f3	4f3047c3-dd2d-4447-9a86-41a25f1ceadf	\N	f	f	\N	f	0
65637ba6-4289-4d41-be59-5b62468b0b26	\N	\N	kaane0169@gmail.com	\N	f	HOs4tZi51Bv7gdLRXCx824egjEEPjoKg+7G/4RXbqU8=	e5614968-18a4-423f-b945-5e5eb48cf9d2	1b6c11cc-5a73-46f5-9165-cb54eae78b81	\N	f	f	\N	f	0
5940e327-bd5c-4749-a5e8-609f5f46bfc5	\N	\N	\N	\N	f	4LbS5YbskmwvFg+OOIReCii+uIVpprFZ0RzqWSNlGeQ=	3f234b4f-2579-4880-a79c-03053b01aea0	ad4d81c3-aa6a-4c13-9a59-1f30183d75d4	\N	f	f	\N	f	0
2cc4c17c-e416-48c5-8853-253424bbd864	\N	\N	{"email":"kaane5662@hstat.org","primary":false,"verified":true,"visibility":null}	\N	f	oLX9UvmzEnXtBhSmmhvUY2tFGNxZhMAR//MGb18DiFk=	9705462e-afe5-4468-84a0-ad073b9de0ef	c582459e-7575-450b-9a3e-ebd122bec9e0	\N	f	f	\N	f	0
afdbcd97-be56-4da5-a8d3-2f9f754dc687	\N	\N	test8@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	3058135a-981e-4394-8272-4adea04d08a6	597ec461-78b5-47c6-b58a-e8c3e0718b5c	\N	f	f	\N	f	0
046e9ff1-dbd7-4ea4-9bab-e3200a7ceef7	\N	\N	test12@gmail.com	\N	f	K67AquK7mCoy/0Hzq6/ImjVGs3mxxAMLEV0BmG1136o=	f6dc154b-8315-4f83-aff3-1d2a3be761fe	1a4f7fb4-73ee-4305-8323-b88cc675329c	\N	f	f	\N	f	0
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240928171954_ProfileNew	8.0.8
20241012153456_ProfileVideoMigrations	8.0.8
20241012211923_ProfileUrls	8.0.8
20241012212332_ProfileUrlsNew	8.0.8
20241109034324_Messages	8.0.8
\.


--
-- Name: DirectMessages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."DirectMessages_Id_seq"', 7, true);


--
-- Name: Messages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Messages_Id_seq"', 147, true);


--
-- Name: Profiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Profiles_Id_seq"', 14, true);


--
-- Name: Project_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Project_Id_seq"', 1, false);


--
-- Name: DirectMessages PK_DirectMessages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DirectMessages"
    ADD CONSTRAINT "PK_DirectMessages" PRIMARY KEY ("Id");


--
-- Name: Messages PK_Messages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "PK_Messages" PRIMARY KEY ("Id");


--
-- Name: Profiles PK_Profiles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id");


--
-- Name: Project PK_Project; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "PK_Project" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Project_ProfileId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Project_ProfileId" ON public."Project" USING btree ("ProfileId");


--
-- Name: Project FK_Project_Profiles_ProfileId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "FK_Project_Profiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES public."Profiles"("Id");


--
-- PostgreSQL database dump complete
--

