interface Constants {
    industries: string[];
    interests: string[];
    languages: string[];
    frameworks: string[];
    roles: string[];
    availability: string[];
    features:string[]
    timezones:string[]
    experience:string[]
    commonSkills:string[]
  }
  
  export const constants: Constants = {
    industries: [
      'Accounting',
      'Advertising',
      'Agriculture',
      'Aerospace',
      'Architecture',
      'Automotive',
      'Banking',
      'Biotechnology',
      'Blockchain',
      'Chemical',
      'Cloud Computing',
      'Construction',
      'Consulting',
      'Cybersecurity',
      'Data Science',
      'Defense',
      'E-commerce',
      'Education',
      'Energy',
      'Entertainment',
      'Environmental Services',
      'Fashion',
      'Finance',
      'Food & Beverage',
      'Gaming',
      'Government',
      'Healthcare',
      'Hospitality',
      'Human Resources',
      'Insurance',
      'Investment Banking',
      'Legal',
      'Logistics',
      'Manufacturing',
      'Marketing',
      'Media & Broadcasting',
      'Mobile Development',
      'Nonprofit',
      'Oil & Gas',
      'Pharmaceutical',
      'Public Relations',
      'Real Estate',
      'Renewable Energy',
      'Retail',
      'Robotics',
      'Shipping & Transportation',
      'Social Media',
      'Sports & Recreation',
      'Technology',
      'Telecommunications',
      'Tourism',
      'Transportation',
      'Venture Capital',
      'Video Production',
      'Web Development',
      'Wealth Management',
      'Waste Management',
    ],
    interests: [
      'Artificial Intelligence (AI)',
      'Blockchain',
      'Cloud Computing',
      'Cybersecurity',
      'Data Science',
      'Internet of Things (IoT)',
      'Machine Learning',
      'Mobile Development',
      'Robotics',
      'Web Development',
    ],
    languages: [
      'JavaScript',
      'TypeScript',
      'Python',
      'C#',
      'Java',
      'Ruby',
      'PHP',
      'C++',
      'Swift',
      'Go',
    ],
    frameworks: [
      "Angular",
      "ASP.NET",
      "Django",
      "Express.js",
      "FastAPI",
      "Flask",
      "Hugging Face Transformers",
      "Laravel",
      "Next.js",
      "PyTorch",
      "React",
      "Ruby on Rails",
      "Spring Boot",
      "Svelte",
      "TensorFlow",
      "Vue.js"
    ],
    roles: [
      'DevOps Engineer',
      'Game Developer',
      'Full Stack Developer',
      'Front-End Developer',
      'Back-End Developer',
      'Data Engineer',
      'Machine Learning Engineer',
      'Cloud Architect',
      'Security Engineer',
      'Student',
      'Mobile Developer',
    ],
    availability: [
      'Full-time',
      'Part-time',
      'Freelance',
      'Contract',
      'Internship',
    ],
    features: [
      'Profile Database',
      'Direct Messages',
      'AI Matches',
      'Video Chat',
      'Profile',
      'Dashboard'
    ],
    timezones: [
      "UTC",
      "GMT",
      "EST (UTC-5)",
      "CST (UTC-6)",
      "MST (UTC-7)",
      "PST (UTC-8)",
      "AST (UTC-4)",
      "HST (UTC-10)",
      "AKST (UTC-9)",
      "EDT (UTC-4)",
      "CDT (UTC-5)",
      "MDT (UTC-6)",
      "PDT (UTC-7)",
      "BST (UTC+1)",
      "CET (UTC+1)",
      "EET (UTC+2)",
      "IST (UTC+5:30)",
      "CST (China, UTC+8)",
      "JST (UTC+9)",
      "AEST (UTC+10)",
      "ACST (UTC+9:30)"
    ],
    experience:["Junior", "Mid-level", "Senior", "Lead", "Architect"],
    commonSkills:["UI/UX Design",
    "Video Editing",
    "Marketing",
    "Sales",
    "Figma",
    "Product Management",
    "Data Analysis",
    "SEO",
    "Content Creation",
    "Project Management",
    "Public Speaking",
    "Customer Support",]
    
  };