interface Constants {
    industries: string[];
    interests: string[];
    languages: string[];
    frameworks: string[];
    roles: string[];
    availability: string[];
  }
  
  export const constants: Constants = {
    industries: [
      'Accounting',
      'Advertising',
      'Agriculture',
      'Aerospace',
      'Architecture',
      'Automotive',
      'Banking',
      'Biotechnology',
      'Blockchain',
      'Chemical',
      'Cloud Computing',
      'Construction',
      'Consulting',
      'Cybersecurity',
      'Data Science',
      'Defense',
      'E-commerce',
      'Education',
      'Energy',
      'Entertainment',
      'Environmental Services',
      'Fashion',
      'Finance',
      'Food & Beverage',
      'Gaming',
      'Government',
      'Healthcare',
      'Hospitality',
      'Human Resources',
      'Insurance',
      'Investment Banking',
      'Legal',
      'Logistics',
      'Manufacturing',
      'Marketing',
      'Media & Broadcasting',
      'Mobile Development',
      'Nonprofit',
      'Oil & Gas',
      'Pharmaceutical',
      'Public Relations',
      'Real Estate',
      'Renewable Energy',
      'Retail',
      'Robotics',
      'Shipping & Transportation',
      'Social Media',
      'Sports & Recreation',
      'Technology',
      'Telecommunications',
      'Tourism',
      'Transportation',
      'Venture Capital',
      'Video Production',
      'Web Development',
      'Wealth Management',
      'Waste Management',
    ],
    interests: [
      'Artificial Intelligence (AI)',
      'Blockchain',
      'Cloud Computing',
      'Cybersecurity',
      'Data Science',
      'Internet of Things (IoT)',
      'Machine Learning',
      'Mobile Development',
      'Robotics',
      'Web Development',
    ],
    languages: [
      'JavaScript',
      'TypeScript',
      'Python',
      'C#',
      'Java',
      'Ruby',
      'PHP',
      'C++',
      'Swift',
      'Go',
    ],
    frameworks: [
      'React',
      'Angular',
      'Vue.js',
      'Django',
      'Flask',
      '.NET',
      'Spring Boot',
      'Ruby on Rails',
      'Next.js',
      'Express',
    ],
    roles: [
      'DevOps Engineer',
      'Game Developer',
      'Full Stack Developer',
      'Front-End Developer',
      'Back-End Developer',
      'Data Engineer',
      'Machine Learning Engineer',
      'Cloud Architect',
      'Security Engineer',
      'Mobile Developer',
    ],
    availability: [
      'Full-time',
      'Part-time',
      'Freelance',
      'Contract',
      'Internship',
    ],
  };